### ISSUE TITLE
如图

### ISSUE THREAD

**Issue by ntm25576** [missdeer/corednshome#5]
![QQ图片20200326194130](https://user-images.githubusercontent.com/28554239/77643155-d1dfb580-6f99-11ea-8e91-7d871862313a.png)

**Comment by conanlm** [comment]
我也是这个问题，求解决

**Comment by missdeer** [comment]
@conanlm 
从其他地方找`libcrypto-1_1-x64.dll`和`libssl-1_1-x64.dll`，放到`corednshome.exe`相同目录下。

**Comment by conanlm** [comment]
> @conanlm
> 从其他地方找`libcrypto-1_1-x64.dll`和`libssl-1_1-x64.dll`，放到`corednshome.exe`相同目录下。

谢谢，解决了
