### ISSUE TITLE
SSL not supported, exit now

### ISSUE THREAD

**Issue by pc10201** [missdeer/corednshome#7]
---------------------------
Critical error
---------------------------
SSL not supported, exit now.
---------------------------
OK   
---------------------------

**Comment by missdeer** [comment]
64位windows：
https://download.qt.io/online/qtsdkrepository/windows_x86/desktop/tools_openssl_x64/qt.tools.openssl.win_x64/1.1.1-4openssl_1.1.1d_prebuild_x64.7z
32位windows：
https://download.qt.io/online/qtsdkrepository/windows_x86/desktop/tools_openssl_x86/qt.tools.openssl.win_x86/1.1.1-4openssl_1.1.1d_prebuild_x86.7z

解压后放在`corednshome.exe` 相同目录。
